"""create executions table

Revision ID: 9d96e3408630
Revises: b9591033fc1e
Create Date: 2026-08-23 02:33:56.358973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d96e3408630'
down_revision: Union[str, Sequence[str], None] = 'b9591033fc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('external_task_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('vendor_id', sa.String(length=100), nullable=False),
    sa.Column('vendor_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('human_reviewed', sa.Boolean(), nullable=False),
    sa.Column('ai_decision', sa.String(length=50), nullable=False),
    sa.Column('final_decision', sa.String(length=50), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('processing_time_seconds', sa.Integer(), nullable=False),
    sa.Column('exception_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'external_task_id', name='uq_agent_external_task')
    )
    op.create_index('ix_executions_agent_confidence', 'executions', ['agent_id', 'confidence'], unique=False)
    op.create_index(op.f('ix_executions_agent_id'), 'executions', ['agent_id'], unique=False)
    op.create_index('ix_executions_agent_timestamp', 'executions', ['agent_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_executions_risk_level'), 'executions', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executions_risk_level'), table_name='executions')
    op.drop_index('ix_executions_agent_timestamp', table_name='executions')
    op.drop_index(op.f('ix_executions_agent_id'), table_name='executions')
    op.drop_index('ix_executions_agent_confidence', table_name='executions')
    op.drop_table('executions')
    # ### end Alembic commands ###
