"""add policies and simulations

Revision ID: f4f2dcbd333e
Revises: 9d96e3408630
Create Date: 2026-08-23 04:10:36.247733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f2dcbd333e'
down_revision: Union[str, Sequence[str], None] = '9d96e3408630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('minimum_confidence', sa.Float(), nullable=False),
    sa.Column('maximum_transaction_value', sa.Float(), nullable=False),
    sa.Column('maximum_error_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_agent_id'), 'policies', ['agent_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('max_transaction_value', sa.Float(), nullable=False),
    sa.Column('max_error_rate', sa.Float(), nullable=False),
    sa.Column('current_autonomy_rate', sa.Float(), nullable=False),
    sa.Column('current_error_rate', sa.Float(), nullable=False),
    sa.Column('proposed_autonomy_rate', sa.Float(), nullable=False),
    sa.Column('proposed_accuracy', sa.Float(), nullable=False),
    sa.Column('proposed_error_rate', sa.Float(), nullable=False),
    sa.Column('autonomous_tasks', sa.Integer(), nullable=False),
    sa.Column('human_reviews', sa.Integer(), nullable=False),
    sa.Column('autonomy_change', sa.Float(), nullable=False),
    sa.Column('human_reviews_saved', sa.Integer(), nullable=False),
    sa.Column('risk_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_agent_id'), 'simulations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_simulations_policy_id'), 'simulations', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_policy_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_agent_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_policies_agent_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
